# Generated by Django 4.1 on 2023-11-17 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="COPDPatients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=30)),
                ("patronymic", models.CharField(max_length=30)),
                ("birthday", models.DateField()),
                ("age", models.PositiveSmallIntegerField(default=0)),
                ("address", models.CharField(max_length=150)),
                ("medical_organization_attachments", models.CharField(max_length=200)),
                (
                    "year_of_diagnosis_of_COPD",
                    models.DateField(default=datetime.date.today),
                ),
                ("disability", models.BooleanField(default=False)),
                ("hospitalization_with_year_with_ICD", models.CharField(max_length=30)),
                ("requests_number_COPD", models.PositiveSmallIntegerField(default=0)),
                (
                    "requests_number_COPD_with_aggravation",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("outpatient_exacerbations", models.CharField(max_length=20)),
                (
                    "vaccination",
                    models.CharField(
                        choices=[("1", "нет"), ("2", "грипп"), ("3", "пневмококк")],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("FEV_FVC_after_bronchodilation", models.CharField(max_length=10)),
                ("OFV1_after_bronchodilation", models.CharField(max_length=200)),
                ("blood_eosinophils", models.FloatField(default=1.0)),
                ("saturation", models.PositiveSmallIntegerField(default=0)),
                (
                    "m_MRC",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4")], default=1
                    ),
                ),
                (
                    "salbutamol",
                    models.CharField(
                        choices=[
                            ("1", "сальбутомол"),
                            ("2", "фенотерол"),
                            ("3", "ипратропия бромид"),
                            ("4", "ипратропия бромид/фенотерол"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "DDBA_DDAHP",
                    models.CharField(
                        choices=[
                            ("1", "Тиотропия бромид/олодатерол"),
                            ("2", "Аклидиний/формотерол"),
                            ("3", "Вилантерол/умеклидиний"),
                            ("4", "Гликопироний/индокатерол "),
                            ("5", "нет"),
                        ],
                        default=5,
                        max_length=1,
                    ),
                ),
                (
                    "IGCS_DDBA",
                    models.CharField(
                        choices=[
                            ("1", "будесонид/формотерол"),
                            ("2", "сальметерол/флутиказон"),
                            ("3", "беклометазон/формотерол"),
                            ("4", "будесонид/формотерол"),
                            ("5", "флутиказон/вилантерол"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "DDAHP",
                    models.CharField(
                        choices=[
                            ("1", "аклидиний"),
                            ("2", "тиотропий"),
                            ("3", "гликопироний"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                (
                    "triple_fixed_combinations",
                    models.CharField(
                        choices=[
                            ("1", "нет"),
                            (
                                "2",
                                "флутиказон фуроат + бромид умеклидиния + вилантерол",
                            ),
                            ("3", "мометазон/гликопирроний/индоктерол"),
                            ("4", "бекламетазон/ гликопирроний/ формотерол"),
                            ("5", "будесонид/ гликопирроний/ формотерол фумарат"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("sputum_sowing", models.CharField(max_length=200)),
                ("ICD", models.PositiveSmallIntegerField(default=0)),
                ("consists_under_DN", models.DateField()),
                (
                    "diseases_per_year",
                    models.CharField(
                        choices=[
                            ("1", "контроль ХОБЛ"),
                            ("2", "ухудшение"),
                            ("3", "смерть"),
                        ],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("cause_of_death", models.TextField()),
                (
                    "dispensary_observation_status",
                    models.CharField(
                        choices=[("1", "Наблюдение"), ("2", "Переехал"), ("3", "Умер")],
                        default=1,
                        max_length=1,
                    ),
                ),
                ("dispensary_observation_date_status", models.DateField()),
            ],
            options={
                "db_table": "COPD_patients",
            },
        ),
    ]
